name: CI

on:
  push:
    # branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  basics:
    strategy:
      matrix:
        node: ['12', '14', '16', '17']
    runs-on: ubuntu-latest
    name: node ${{ matrix.node }}
    env:
      LATEST_NODE: '17'

    steps:
    - name: git clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: yarn install-all:ci
    - run: yarn test
